# Generated by Django 2.1.2 on 2018-10-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='capacity',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='food',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='medicine',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='water',
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
