# Generated by Django 2.1.2 on 2018-10-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_hazard'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='name',
            field=models.CharField(default='camp', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camp',
            name='place_id',
            field=models.CharField(default='null', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camp',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='camp',
            name='description',
            field=models.TextField(blank=True, default='We provide food, shelter and protection. All are welcome.', null=True),
        ),
    ]
