# Generated by Django 2.1.2 on 2018-10-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20181016_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='name',
        ),
    ]
