# Generated by Django 2.1.2 on 2018-10-17 10:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_camp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('emergencyName', models.CharField(max_length=32, null=True)),
                ('emergencyPhone', models.CharField(max_length=32, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Camp')),
            ],
        ),
    ]
