# Generated by Django 2.1.2 on 2018-10-18 07:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='description',
            field=models.TextField(default='Compromised area, keep distance', null=True),
        ),
        migrations.AddField(
            model_name='hazard',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
