# Generated by Django 2.1.2 on 2018-10-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_person_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='checkin',
        ),
    ]
